# Generated by Django 6.0 on 2025-12-15 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        default="",
                        max_length=150,
                        null=True,
                        verbose_name="Название категории",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Название товара"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "characteristic",
                    models.TextField(blank=True, verbose_name="Характеристика"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="product_im", verbose_name="Изображение"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                ("rating", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="Game_app.category",
                    ),
                ),
            ],
        ),
    ]
